export const adminRoutes = [
  { path: "/admin/proposals", component: "project-proposals" },
  { path: "/admin/pending", component: "pending-projects" },
  { path: "/admin/project/:id", component: "project-dashboard" },
  {
    path: "/admin/project/:id/requirements",
    component: "project-requirements",
  },
  { path: "/admin/project/:id/designs", component: "project-designs" },
  { path: "/admin/project/:id/devtasks", component: "project-devtasks" },
  { path: "/admin/project/:id/tests", component: "project-tests" },
  { path: "/admin/project/:id/releases", component: "project-releases" },
  { path: "/admin/project/:id/maintenance", component: "project-maintenance" },
  { path: "/admin/inprogress", component: "inprogress-projects" },
  { path: "/admin/complted", component: "project-complted-page" },
  { path: "/admin/maintenance", component: "project-maintenance-page" },
  { path: "/admin/rejected", component: "rejected-proposals" },
  { path: "/admin", component: "admin-dashboard" },
  { path: "/admin/login", component: "admin-login-page" },
  { path: "/admin/assigndeveloper", component: "assign-developer-page" },
  { path: "/admin/projectrequirement", component: "project-requirement-page" },
  { path: "/admin/projectdesign", component: "project-design-page" },
  { path: "/admin/reportspage", component: "reports-page" },
  { path: "/admin/clientdetailspage", component: "client-details-page" },
  { path: "/admin/clientSpage", component: "clients-page" },
  { path: "/admin/empdetailspage", component: "employee-details-page" },
  { path: "/admin/employeepage", component: "employee-page" },
  { path: "/admin/financepage", component: "finance-page" },
  { path: "/admin/addExpenses", component: "add-expenses" },
  { path: "/admin/addNewExpense", component: "add-new-expense" },
];

export const clientRoutes = [
  // action: validateClient,
  { path: "/client", component: "client-dashboard-page" },
  { path: "/client/login", component: "client-login-page" },
  { path: "/client/messages", component: "message-page" },
  { path: "/client/sendmessage", component: "send-message-page" },
  { path: "/client/project/features", component: "features-page" },
  { path: "/client/project/addfeature", component: "add-feature-page" },
  { path: "/client/project/addinvoice", component: "add-invoice-page" },
  { path: "/client/project/addfeedback", component: "add-feedback-page" },
  { path: "/client/project/addissue", component: "add-issue-page" },
  { path: "/client/project/issues", component: "issues-page" },
  { path: "/client/project/invoices", component: "invoice-page" },
  { path: "/client/project/agreements", component: "agreements-page" },
  { path: "/client/project/feedback", component: "feedback-page" },
  { path: "/client/requestproject", component: "request-project-page" },
  { path: "/client/project/:id", component: "client-project-page" },
  { path: "/client/projects", component: "client-projects-page" },
  { path: "/client/profile", component: "client-profile-page" },
];
